kind: pipeline
name: 编译发布

steps:
- name: 恢复缓存
  image: meltwater/drone-cache:dev
  pull: true
  settings:
    backend: "filesystem"
    restore: true
    cache_key: "{{ .Commit.Branch }}"
    archive_format: "gzip"
    mount:
      - 'dl'
      - 'feeds'
  volumes:
    - name: cache
      path: /tmp/cache
- name: 编译构建
  image: tossp/lede
  pull: true
  environment:
    FORCE_UNSAFE_CONFIGURE: 1
    GOPROXY: https://mirrors.aliyun.com/goproxy/
  commands:
    - mkdir -p ${DRONE_REPO_OWNER}_${DRONE_REPO_NAME}_build
    - echo '' > ${DRONE_REPO_OWNER}_${DRONE_REPO_NAME}_build/${DRONE_COMMIT_SHA}.build.txt
    - sed -i "s/CI_COMMIT_SHA/${DRONE_COMMIT_SHA}/g" ./package/ts/default-settings/files/zzz-default-settings
    - sed -i "s/COMMIT_SHA_VERSION/${DRONE_COMMIT_SHA:0:8}/g" ./package/ts/default-settings/Makefile
    - ./scripts/feeds update -a && ./scripts/feeds install -a
    - cp k3.config .config && make defconfig
    - (make -j4 V=sc 2>&1 | tee ${DRONE_REPO_OWNER}_${DRONE_REPO_NAME}_build/${DRONE_COMMIT_SHA}.build.txt | grep -E -e "time.+(#[\.0-9]+){3}" -e 'make\[[0-9]\].{2}(Leav|Enter)ing directory.+') || (grep -P 'Error \d+\b(?! \(ignored\))' -C5 ${DRONE_REPO_OWNER}_${DRONE_REPO_NAME}_build/${DRONE_COMMIT_SHA}.build.txt && exit 66)
    - rm -rf build_dir/target-arm_cortex-a9_musl_eabi staging_dir/target-arm_cortex-a9_musl_eabi
  when:
    branch:
      - ci
- name: 重建缓存
  image: meltwater/drone-cache:dev
  pull: true
  settings:
    backend: "filesystem"
    rebuild: true
    cache_key: "{{ .Commit.Branch }}"
    archive_format: "gzip"
    mount:
      - 'dl'
      - 'feeds'
  volumes:
    - name: cache
      path: /tmp/cache
- name: 发布部署
  image: tossp/lede
  environment:
    QN_AK:
      from_secret: qn_ak
    QN_SK:
      from_secret: qn_sk
  commands:
    - wget -O /bin/qshell http://devtools.qiniu.com/2.1.5/qshell-linux-x64
    - chmod a+x /bin/qshell
    - echo $QN_AK $QN_SK
    - qshell account $QN_AK $QN_SK
    - qshell qupload2 -log-file qshell.log -check-exists -check-hash -check-size -overwrite -rescan-local -src-dir ${DRONE_REPO_OWNER}_${DRONE_REPO_NAME}_build -bucket lede-k3
    - cp ${DRONE_REPO_OWNER}_${DRONE_REPO_NAME}_build/${DRONE_COMMIT_SHA}.build.txt bin/build.txt
    - cp .config bin/config.txt
    - cp bin/targets/bcm53xx/generic/sha256sums bin/targets/bcm53xx/generic/sha256sums.txt
    - cp index.tpl bin/index.html
    - tree -L 5 bin/ > bin/tree.txt
    - TSTIME=`date '+%Y-%m-%d %H:%M:%S' -d '8 hours'`
    - sed -i "s/CI_COMMIT_SHA/${DRONE_COMMIT_SHA}/g" bin/index.html
    - sed -i "s/CI_RUNNER_DESCRIPTION/${DRONE_RUNNER_HOST}/g" bin/index.html
    - sed -i "s/CI_RUNNER_TAGS/${DRONE_COMMIT_AUTHOR_NAME}/g" bin/index.html
    - sed -i "s/CI_BUILD_TIME/$TSTIME/g" bin/index.html
    - mkdir -p ${DRONE_COMMIT_SHA}
    - mv -f bin/* ${DRONE_COMMIT_SHA}
    - mv -f ${DRONE_COMMIT_SHA} bin/
    - cp bin/${DRONE_COMMIT_SHA}/index.html bin/
    - qshell qupload2 -log-file qshell.log -check-exists -check-hash -check-size -overwrite -rescan-local -thread-count $(nproc) -src-dir bin -bucket lede-k3
    - rm -rf bin/${DRONE_COMMIT_SHA}/
    - qshell listbucket lede-k3 his
    - grep '/index.html' his | sort -k4 -r | awk 'BEGIN{FS="[/\t]"} {print "{\"id\":\""$1"\",\"time\":\""$5"\",\"src\":\"openwrt\",\"target\":\"k3\"}\n,"}' | sed -e '1i [' -e '$c ]' > bin/history.json
    - qshell qupload2 -log-file qshell.log -check-exists -check-hash -check-size -overwrite -rescan-local -thread-count 6 -src-dir bin -bucket lede-k3
    - qshell cdnrefresh refresh.list
    - cat qshell.log | grep -Ev ' \[I\] [A-Z]'
trigger:
  branch:
  - ci
volumes:
  - name: cache
    host:
      path: /root/ts/compose/drone/cache
