kind: pipeline
name: lede-K3

steps:
- name: 发布部署
  image: tossp/lede
  environment:
    QN_AK:
      from_secret: qn_ak
    QN_SK:
      from_secret: qn_sk
  commands:
    - cp index.tmpl bin/index.html
    - tree -L 5 bin/ > bin/tree.txt
    - TSTIME=`date '+%Y-%m-%d %H:%M:%S' -d '8 hours'`
    - sed -i "s/CI_COMMIT_SHA/${DRONE_COMMIT_SHA}/g" bin/index.html
    - sed -i "s/CI_RUNNER_DESCRIPTION/${DRONE_RUNNER_HOST}/g" bin/index.html
    - sed -i "s/CI_RUNNER_TAGS/${DRONE_COMMIT_AUTHOR_NAME}/g" bin/index.html
    - sed -i "s/CI_BUILD_TIME/$TSTIME/g" bin/index.html
    - mkdir -p ${DRONE_COMMIT_SHA}
    - mv -f bin/* ${DRONE_COMMIT_SHA}
    - mv -f ${DRONE_COMMIT_SHA} bin/
    - cp bin/${DRONE_COMMIT_SHA}/index.html bin/
    - wget -O /bin/qshell http://devtools.qiniu.com/2.1.5/qshell-linux-x64
    - chmod a+x /bin/qshell
    - echo $QN_AK
    - echo $QN_AK
    - qshell account $QN_AK $QN_AK
    - sleep 3600
    - qshell qupload2 -log-file qshell.log -check-exists -check-hash -check-size -overwrite -rescan-local -thread-count 6 -src-dir bin -bucket lede-k3
    - rm -rf bin/$DRONE_COMMIT_SHA/
    - qshell listbucket lede-k3 his 
    - grep '/index.html' his | sort -k4 -r | awk 'BEGIN{FS="[/\t]"} {print "{\"id\":\""$1"\",\"time\":\""$5"\"}\n,"}' | sed -e '1i [' -e '$c ]' > bin/history.json
    - qshell qupload2 -log-file qshell.log -check-exists -check-hash -check-size -overwrite -rescan-local -thread-count 6 -src-dir bin -bucket lede-k3
    - qshell cdnrefresh refresh.list
    - cat qshell.log | grep -Ev ' \[I\] [A-Z]'
trigger:
  branch:
  - ci
volumes:
  - name: cache
    host:
      path: /root/ts/compose/drone/cache