#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].hostname=tsk3
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab


uci set minidlna.config.enabled=0
uci commit minidlna
/etc/init.d/minidlna disable
/etc/init.d/minidlna stop

ln -sf /sbin/ip /usr/bin/ip

sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i '/openwrt_custom/d' /etc/opkg/distfeeds.conf
sed -i 's/downloads.openwrt.org/openwrt.proxy.ustclug.org/g' /etc/opkg/distfeeds.conf
sed -i 's/http/https/g' /etc/opkg/distfeeds.conf
# sed -i "s/# //g" /etc/opkg/distfeeds.conf
opkg_items_version='CI_COMMIT_SHA'
sed -i '/tossp_k3_/d' /etc/opkg/distfeeds.conf
echo "src/gz tossp_k3_core http://lede-k3.test.tossp.com/${opkg_items_version}/targets/bcm53xx/generic/packages" >> /etc/opkg/distfeeds.conf
opkg_items="base luci packages routing custom"
for item in ${opkg_items}; do echo "src/gz tossp_k3_${item} http://lede-k3.test.tossp.com/${opkg_items_version}/packages/arm_cortex-a9/${item}" >> /etc/opkg/distfeeds.conf; done


uci set dhcp.lan.ra='server'
uci set dhcp.lan.dhcpv6='server'
uci set dhcp.lan.ra_management='1'
uci set dhcp.lan.ra_default='1'
uci commit dhcp

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up


sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

sed -i '/DISTRIB_TOSSP_COM/d' /etc/openwrt_release
echo "DISTRIB_TOSSP_COM_REVISION='CI_COMMIT_SHA'" >> /etc/openwrt_release
echo "REVISION='CI_COMMIT_SHA'" > /etc/ts_release
chmod -R a+r,a+X /www

exit 0